{% set version = '0.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-crew.cluster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/crew.cluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/crew.cluster/crew.cluster_{{ version }}.tar.gz
  sha256: 6805ea476f0765330f6918d93be72381cb6613b10b40fc65cba900460c99341b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-crew >=0.8.0
    - r-lifecycle
    - r-ps
    - r-rlang
    - r-vctrs
    - r-xml2
  run:
    - r-base
    - r-r6
    - r-crew >=0.8.0
    - r-lifecycle
    - r-ps
    - r-rlang
    - r-vctrs
    - r-xml2

test:
  commands:
    - $R -e "library('crew.cluster')"           # [not win]
    - "\"%R%\" -e \"library('crew.cluster')\""  # [win]

about:
  home: https://wlandau.github.io/crew.cluster/
  dev_url: https://github.com/wlandau/crew.cluster
  license: MIT
  summary: In computationally demanding analysis projects, statisticians and data scientists
    asynchronously deploy long-running tasks to distributed systems, ranging from traditional
    clusters to cloud services. The 'crew.cluster' package extends the 'mirai'-powered
    'crew' package with worker launcher plugins for traditional high-performance computing
    systems. Inspiration also comes from packages 'mirai' by Gao (2023) <https://github.com/shikokuchuo/mirai>,
    'future' by Bengtsson (2021) <doi:10.32614/RJ-2021-048>, 'rrq' by FitzJohn and Ashton
    (2023) <https://github.com/mrc-ide/rrq>, 'clustermq' by Schubert (2019) <doi:10.1093/bioinformatics/btz284>),
    and 'batchtools' by Lang, Bischl, and Surmann (2017). <doi:10.21105/joss.00135>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: crew.cluster
# Title: Crew Launcher Plugins for Traditional High-Performance Computing Clusters
# Description: In computationally demanding analysis projects, statisticians and data scientists asynchronously deploy long-running tasks to distributed systems, ranging from traditional clusters to cloud services. The 'crew.cluster' package extends the 'mirai'-powered 'crew' package with worker launcher plugins for traditional high-performance computing systems. Inspiration also comes from packages 'mirai' by Gao (2023) <https://github.com/shikokuchuo/mirai>, 'future' by Bengtsson (2021) <doi:10.32614/RJ-2021-048>, 'rrq' by FitzJohn and Ashton (2023) <https://github.com/mrc-ide/rrq>, 'clustermq' by Schubert (2019) <doi:10.1093/bioinformatics/btz284>), and 'batchtools' by Lang, Bischl, and Surmann (2017). <doi:10.21105/joss.00135>.
# Version: 0.3.0
# License: MIT + file LICENSE
# URL: https://wlandau.github.io/crew.cluster/, https://github.com/wlandau/crew.cluster
# BugReports: https://github.com/wlandau/crew.cluster/issues
# Authors@R: c( person( given = c("William", "Michael"), family = "Landau", role = c("aut", "cre"), email = "will.landau.oss@gmail.com", comment = c(ORCID = "0000-0003-1878-3253") ), person( given = c("Michael", "Gilbert"), family = "Levin", role = "aut", email = "mglev1n@gmail.com", comment = c(ORCID = "0000-0002-9937-9932") ), person( family = "Eli Lilly and Company", role = "cph" ))
# Depends: R (>= 4.0.0)
# Imports: crew (>= 0.8.0), ps, lifecycle, R6, rlang, utils, vctrs, xml2
# Suggests: knitr (>= 1.30), markdown (>= 1.1), rmarkdown (>= 2.4), testthat (>= 3.0.0)
# Encoding: UTF-8
# Language: en-US
# Config/testthat/edition: 3
# RoxygenNote: 7.3.0
# NeedsCompilation: no
# Packaged: 2024-02-07 13:48:03 UTC; C240390
# Author: William Michael Landau [aut, cre] (<https://orcid.org/0000-0003-1878-3253>), Michael Gilbert Levin [aut] (<https://orcid.org/0000-0002-9937-9932>), Eli Lilly and Company [cph]
# Maintainer: William Michael Landau <will.landau.oss@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-02-08 04:20:02 UTC
